services:
  - type: web
    name: dass21-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dass21-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production